//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shumakov_Telecom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestPriority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestPriority()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int PriorityId { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        
        private static readonly Dictionary<RequestPriorityType, string> PriorityColors = new Dictionary<RequestPriorityType, string>
        {
            { RequestPriorityType.Low, "#2ECC71" },
            { RequestPriorityType.Medium, "#FACC15" },
            { RequestPriorityType.High, "#FB923C" },
            { RequestPriorityType.Critical, "#EF4444" },
        };

        public string PriorityColor
        {
            get
            {
                if (PriorityColors.TryGetValue((RequestPriorityType)PriorityId, out var color))
                {
                    return color;
                }
                return "#95A5A6";
            }
        }
    }

    public enum RequestPriorityType
    {
        Low = 1,
        Medium,
        High,
        Critical
    }
}
