//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shumakov_Telecom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestStatus()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int StatusId { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }

        private static readonly Dictionary<RequestStatusType, string> StatusColors = new Dictionary<RequestStatusType, string>
        {
            { RequestStatusType.New, "#3498DB" },
            { RequestStatusType.Assigned, "#1ABC9C" },
            { RequestStatusType.InProgress, "#F1C40F" },
            { RequestStatusType.Completed, "#2ECC71" },
            { RequestStatusType.Closed, "#95A5A6" },
            { RequestStatusType.Cancelled, "#E67E22" }
        };

        public string StatusColor
        {
            get
            {
                if (StatusColors.TryGetValue((RequestStatusType)StatusId, out var color))
                {
                    return color;
                }
                return "#95A5A6";
            }
        }
    }

    public enum RequestStatusType
    {
        New = 1,
        Assigned = 2,
        InProgress = 3,
        Completed = 4,
        Closed = 5,
        Cancelled = 6
    }
}
