//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shumakov_Telecom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Services = new HashSet<Service>();
        }
    
        public int RequestId { get; set; }
        public int StatusId { get; set; }
        public int RequestTypeId { get; set; }
        public int PriorityId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Description { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual RequestPriority RequestPriority { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual RequestType RequestType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
    }
}
